name             'windows_gui_service'
maintainer       'Tomasz Setkowski'
maintainer_email 'tom@ai-traders.com'
license          'MIT'
description      'Chef cookbook to deal with running GUI applications as windows service'
long_description 'Helps to set up auto-login and services to run at windows start up'
version          '0.1.0'
